package com.vuoncog.converter.repository

import com.vuoncog.converter.ui.models.ConversionSymbol
import com.vuoncog.data.models.ErrorTag
import com.vuoncog.data.models.STATUS
import com.vuoncog.data.repository.ConversionRepository
import com.vuoncog.data.response.ExchangeRateResponse
import com.vuoncog.data.response.SymbolsResponse
import javax.inject.Inject

class ConversionUiRepository @Inject constructor(
    private val conversionRepository: ConversionRepository
) {
    suspend fun symbolDataToUiData(
        onSuccess: (List<ConversionSymbol>) -> Unit,
        onError: (ErrorTag?) -> Unit
    ) {
        val data = conversionRepository.getAllSymbols()
        if (data.status == STATUS.SUCCESS) {
            val uiData = (data.data?.toMap()?.map {
                it.value?.let { detail ->
                    ConversionSymbol(
                        symbols = it.key,
                        detail = detail,
                    )
                }
            })?.filterNotNull()
            onSuccess(uiData ?: emptyList())
        } else {
            onError(data.error)
        }
    }

    suspend fun getExchangeRate(
        symbols: List<String>,
        onSuccess: (Map<String, Double?>) -> Unit,
        onError: (ErrorTag?) -> Unit
    ){
        val data = conversionRepository.getExchangeRate(symbols)
        if (data.status == STATUS.SUCCESS){
            val uiData = (data.data?.toMap() ?: emptyMap())
            onSuccess(uiData)
        } else {
            onError(data.error)
        }
    }
}

fun ExchangeRateResponse.Rates.toMap(): Map<String, Double?> {
    return mapOf(
        "AED" to AED,
        "AFN" to AFN,
        "ALL" to ALL,
        "AMD" to AMD,
        "ANG" to ANG,
        "AOA" to AOA,
        "ARS" to ARS,
        "AUD" to AUD,
        "AWG" to AWG,
        "AZN" to AZN,
        "BAM" to BAM,
        "BBD" to BBD,
        "BDT" to BDT,
        "BGN" to BGN,
        "BHD" to BHD,
        "BIF" to BIF,
        "BMD" to BMD,
        "BND" to BND,
        "BOB" to BOB,
        "BRL" to BRL,
        "BSD" to BSD,
        "BTC" to BTC,
        "BTN" to BTN,
        "BWP" to BWP,
        "BYN" to BYN,
        "BYR" to BYR,
        "BZD" to BZD,
        "CAD" to CAD,
        "CDF" to CDF,
        "CHF" to CHF,
        "CLF" to CLF,
        "CLP" to CLP,
        "CNY" to CNY,
        "CNH" to CNH,
        "COP" to COP,
        "CRC" to CRC,
        "CUC" to CUC,
        "CUP" to CUP,
        "CVE" to CVE,
        "CZK" to CZK,
        "DJF" to DJF,
        "DKK" to DKK,
        "DOP" to DOP,
        "DZD" to DZD,
        "EGP" to EGP,
        "ERN" to ERN,
        "ETB" to ETB,
        "EUR" to EUR,
        "FJD" to FJD,
        "FKP" to FKP,
        "GBP" to GBP,
        "GEL" to GEL,
        "GGP" to GGP,
        "GHS" to GHS,
        "GIP" to GIP,
        "GMD" to GMD,
        "GNF" to GNF,
        "GTQ" to GTQ,
        "GYD" to GYD,
        "HKD" to HKD,
        "HNL" to HNL,
        "HRK" to HRK,
        "HTG" to HTG,
        "HUF" to HUF,
        "IDR" to IDR,
        "ILS" to ILS,
        "IMP" to IMP,
        "INR" to INR,
        "IQD" to IQD,
        "IRR" to IRR,
        "ISK" to ISK,
        "JEP" to JEP,
        "JMD" to JMD,
        "JOD" to JOD,
        "JPY" to JPY,
        "KES" to KES,
        "KGS" to KGS,
        "KHR" to KHR,
        "KMF" to KMF,
        "KPW" to KPW,
        "KRW" to KRW,
        "KWD" to KWD,
        "KYD" to KYD,
        "KZT" to KZT,
        "LAK" to LAK,
        "LBP" to LBP,
        "LKR" to LKR,
        "LRD" to LRD,
        "LSL" to LSL,
        "LTL" to LTL,
        "LVL" to LVL,
        "LYD" to LYD,
        "MAD" to MAD,
        "MDL" to MDL,
        "MGA" to MGA,
        "MKD" to MKD,
        "MMK" to MMK,
        "MNT" to MNT,
        "MOP" to MOP,
        "MRU" to MRU,
        "MUR" to MUR,
        "MVR" to MVR,
        "MWK" to MWK,
        "MXN" to MXN,
        "MYR" to MYR,
        "MZN" to MZN,
        "NAD" to NAD,
        "NGN" to NGN,
        "NIO" to NIO,
        "NOK" to NOK,
        "NPR" to NPR,
        "NZD" to NZD,
        "OMR" to OMR,
        "PAB" to PAB,
        "PEN" to PEN,
        "PGK" to PGK,
        "PHP" to PHP,
        "PKR" to PKR,
        "PLN" to PLN,
        "PYG" to PYG,
        "QAR" to QAR,
        "RON" to RON,
        "RSD" to RSD,
        "RUB" to RUB,
        "RWF" to RWF,
        "SAR" to SAR,
        "SBD" to SBD,
        "SCR" to SCR,
        "SDG" to SDG,
        "SEK" to SEK,
        "SGD" to SGD,
        "SHP" to SHP,
        "SLE" to SLE,
        "SLL" to SLL,
        "SOS" to SOS,
        "SRD" to SRD,
        "STD" to STD,
        "SVC" to SVC,
        "SYP" to SYP,
        "SZL" to SZL,
        "THB" to THB,
        "TJS" to TJS,
        "TMT" to TMT,
        "TND" to TND,
        "TOP" to TOP,
        "TRY" to TRY,
        "TTD" to TTD,
        "TWD" to TWD,
        "TZS" to TZS,
        "UAH" to UAH,
        "UGX" to UGX,
        "USD" to USD,
        "UYU" to UYU,
        "UZS" to UZS,
        "VEF" to VEF,
        "VES" to VES,
        "VND" to VND,
        "VUV" to VUV,
        "WST" to WST,
        "XAF" to XAF,
        "XAG" to XAG,
        "XAU" to XAU,
        "XCD" to XCD,
        "XDR" to XDR,
        "XOF" to XOF,
        "XPF" to XPF,
        "YER" to YER,
        "ZAR" to ZAR,
        "ZMK" to ZMK,
        "ZMW" to ZMW,
        "ZWL" to ZWL
    )
}

fun SymbolsResponse.Symbols.toMap(): Map<String, String?> {
    return mapOf(
        "AED" to AED,
        "AFN" to AFN,
        "ALL" to ALL,
        "AMD" to AMD,
        "ANG" to ANG,
        "AOA" to AOA,
        "ARS" to ARS,
        "AUD" to AUD,
        "AWG" to AWG,
        "AZN" to AZN,
        "BAM" to BAM,
        "BBD" to BBD,
        "BDT" to BDT,
        "BGN" to BGN,
        "BHD" to BHD,
        "BIF" to BIF,
        "BMD" to BMD,
        "BND" to BND,
        "BOB" to BOB,
        "BRL" to BRL,
        "BSD" to BSD,
        "BTC" to BTC,
        "BTN" to BTN,
        "BWP" to BWP,
        "BYN" to BYN,
        "BYR" to BYR,
        "BZD" to BZD,
        "CAD" to CAD,
        "CDF" to CDF,
        "CHF" to CHF,
        "CLF" to CLF,
        "CLP" to CLP,
        "CNY" to CNY,
        "CNH" to CNH,
        "COP" to COP,
        "CRC" to CRC,
        "CUC" to CUC,
        "CUP" to CUP,
        "CVE" to CVE,
        "CZK" to CZK,
        "DJF" to DJF,
        "DKK" to DKK,
        "DOP" to DOP,
        "DZD" to DZD,
        "EGP" to EGP,
        "ERN" to ERN,
        "ETB" to ETB,
        "EUR" to EUR,
        "FJD" to FJD,
        "FKP" to FKP,
        "GBP" to GBP,
        "GEL" to GEL,
        "GGP" to GGP,
        "GHS" to GHS,
        "GIP" to GIP,
        "GMD" to GMD,
        "GNF" to GNF,
        "GTQ" to GTQ,
        "GYD" to GYD,
        "HKD" to HKD,
        "HNL" to HNL,
        "HRK" to HRK,
        "HTG" to HTG,
        "HUF" to HUF,
        "IDR" to IDR,
        "ILS" to ILS,
        "IMP" to IMP,
        "INR" to INR,
        "IQD" to IQD,
        "IRR" to IRR,
        "ISK" to ISK,
        "JEP" to JEP,
        "JMD" to JMD,
        "JOD" to JOD,
        "JPY" to JPY,
        "KES" to KES,
        "KGS" to KGS,
        "KHR" to KHR,
        "KMF" to KMF,
        "KPW" to KPW,
        "KRW" to KRW,
        "KWD" to KWD,
        "KYD" to KYD,
        "KZT" to KZT,
        "LAK" to LAK,
        "LBP" to LBP,
        "LKR" to LKR,
        "LRD" to LRD,
        "LSL" to LSL,
        "LTL" to LTL,
        "LVL" to LVL,
        "LYD" to LYD,
        "MAD" to MAD,
        "MDL" to MDL,
        "MGA" to MGA,
        "MKD" to MKD,
        "MMK" to MMK,
        "MNT" to MNT,
        "MOP" to MOP,
        "MRU" to MRU,
        "MUR" to MUR,
        "MVR" to MVR,
        "MWK" to MWK,
        "MXN" to MXN,
        "MYR" to MYR,
        "MZN" to MZN,
        "NAD" to NAD,
        "NGN" to NGN,
        "NIO" to NIO,
        "NOK" to NOK,
        "NPR" to NPR,
        "NZD" to NZD,
        "OMR" to OMR,
        "PAB" to PAB,
        "PEN" to PEN,
        "PGK" to PGK,
        "PHP" to PHP,
        "PKR" to PKR,
        "PLN" to PLN,
        "PYG" to PYG,
        "QAR" to QAR,
        "RON" to RON,
        "RSD" to RSD,
        "RUB" to RUB,
        "RWF" to RWF,
        "SAR" to SAR,
        "SBD" to SBD,
        "SCR" to SCR,
        "SDG" to SDG,
        "SEK" to SEK,
        "SGD" to SGD,
        "SHP" to SHP,
        "SLE" to SLE,
        "SLL" to SLL,
        "SOS" to SOS,
        "SRD" to SRD,
        "STD" to STD,
        "SVC" to SVC,
        "SYP" to SYP,
        "SZL" to SZL,
        "THB" to THB,
        "TJS" to TJS,
        "TMT" to TMT,
        "TND" to TND,
        "TOP" to TOP,
        "TRY" to TRY,
        "TTD" to TTD,
        "TWD" to TWD,
        "TZS" to TZS,
        "UAH" to UAH,
        "UGX" to UGX,
        "USD" to USD,
        "UYU" to UYU,
        "UZS" to UZS,
        "VEF" to VEF,
        "VES" to VES,
        "VND" to VND,
        "VUV" to VUV,
        "WST" to WST,
        "XAF" to XAF,
        "XAG" to XAG,
        "XAU" to XAU,
        "XCD" to XCD,
        "XDR" to XDR,
        "XOF" to XOF,
        "XPF" to XPF,
        "YER" to YER,
        "ZAR" to ZAR,
        "ZMK" to ZMK,
        "ZMW" to ZMW,
        "ZWL" to ZWL
    )
}